# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-04-14T10:52:40Z"
  labels:
    app: postgre-sql
  name: postgre-sql
spec:
  containers:
  - env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: admin@admin.com
    - name: PGADMIN_DEFAULT_PASSWORD
      value: root
    image: docker.io/dpage/pgadmin4:latest
    name: pgadmin
    ports:
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 80
      hostPort: 9876
    resources: {}
    securityContext: {}
    volumeMounts:
    - mountPath: /var/lib/pgadmin
      name: 0aa3c009c18048b6071d9bb479a657a93a5b9b45df49fe98405d3493360021d3-pvc
  - args:
    - postgres
    env:
    - name: POSTGRES_PASSWORD
      value: root
    - name: POSTGRES_USER
      value: admin@admin.com
    image: docker.io/library/postgres:14
    name: pgdatabase
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pg-data-pvc
  hostname: postgre-sql
  restartPolicy: Never
  volumes:
  - name: 0aa3c009c18048b6071d9bb479a657a93a5b9b45df49fe98405d3493360021d3-pvc
    persistentVolumeClaim:
      claimName: 0aa3c009c18048b6071d9bb479a657a93a5b9b45df49fe98405d3493360021d3
  - name: pg-data-pvc
    persistentVolumeClaim:
      claimName: pg-data
status: {}
