FROM docker.io/python:3
# FROM prefecthq/prefect:2.7.7-python3.9

COPY ./prefect-requirements.txt ~/

# RUN pip install -r prefect-requirements.txt --trusted-host pypi.python.org --no-cache-dir
# RUN mkdir /opt/prefect/flows

# COPY flows/02_gcp/parameterised_flow.py /opt/prefect/flows/parameterised_flow.py